### ISSUE TITLE
can not delete photos by the method "deleteFile"

### ISSUE THREAD

**Issue by henryyohn** [ricohapi/theta-plugin-camera-api-sample#10]
I got the photo fileId by camera.getList(), then I would like to delete the photo by  method "deleteFile" with the photo file id  from thetasc2 camera. It will always fail: file not found.
`W/System.err: java.io.FileNotFoundException: http://192.168.1.1/osc/commands/execute
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
W/System.err:     at com.krpano100.theta.network.HttpConnector.deleteFile(HttpConnector.java:601)
W/System.err:     at com.krpano100.theta.ImageListActivity$DeleteObjectTask.doInBackground(ImageListActivity.java:469)
W/System.err:     at com.krpano100.theta.ImageListActivity$DeleteObjectTask.doInBackground(ImageListActivity.java:457)
W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:923)`

can anyone give me some advice.
thank you so much!

**Comment by DaisukeHohjoh** [comment]
Dear Mr. henryyohn,

We appreciate your input and apologize for the lack of updates.
As there hasn't been any activity on this issue for a prolonged period, we will be closing it for now.
Should you have further questions or if the issue persists, please don't hesitate to reopen or comment.

Best Regards,
Daisuke Hohjoh
